import type { FastifyInstance } from 'fastify'
import { healthRoutes } from './health.routes'
import { authRoutes } from './auth.routes'
import { marketplaceRoutes } from './marketplace.routes'
import { adRoutes } from './ad.routes'
import { tradeRoutes } from './trade.routes'
import { walletRoutes } from './wallet.routes'
import { kycRoutes } from './kyc.routes'
import { userRoutes } from './user.routes'
import { dashboardRoutes } from './dashboard.routes'
import { merchantRoutes } from './merchant.routes'
import { instantBuyRoutes } from './instantBuy.routes'
import { disputeRoutes } from './dispute.routes'
import { notificationRoutes } from './notification.routes'
import { referralRoutes } from './referral.routes'
import { leaderboardRoutes } from './leaderboard.routes'
import { uploadRoutes } from './upload.routes'
import { webhookRoutes } from './webhook.routes'
import { rateAlertRoutes } from './rateAlert.routes'
import { savedTermsRoutes } from './savedTerms.routes'
import { gasFeeRoutes } from './gasFee.routes'
import { merchantGasRoutes } from './merchantGas.routes'
import { adminRoutes } from './admin.routes'
import { ctmTokenRoutes } from '../ctm/ctm.token.routes'
import { ctmListingRoutes } from '../ctm/ctm.listing.routes'
import { ctmRequestRoutes } from '../ctm/ctm.request.routes'
import { ctmTradeRoutes } from '../ctm/ctm.trade.routes'
import { ctmMerchantRoutes } from '../ctm/ctm.merchant.routes'
import { ctmAdminRoutes } from '../ctm/ctm.admin.routes'
import { ctmBidRoutes } from '../ctm/ctm.bid.routes'
import { adBidRoutes } from './ad.bid.routes'
import { pushRoutes } from './push.routes'
import { sseRoutes } from './sse.routes'
import { adminNotificationRoutes } from './adminNotification.routes'
import { logosRoutes } from './logos.routes'
import { supportRoutes } from './support.routes'
import { appealRoutes } from './appeal.routes'
import { telegramRoutes } from './telegram.routes'
import { accountLinkRoutes } from './accountLink.routes'
import { announcementRoutes } from './announcement.routes'
import { blogRoutes } from './blog.routes'
import { airdropRoutes } from './airdrop.routes'

export async function registerRoutes(app: FastifyInstance) {
  await app.register(healthRoutes)
  await app.register(authRoutes, { prefix: '/api/v1/auth' })
  await app.register(marketplaceRoutes, { prefix: '/api/v1/marketplace' })
  await app.register(adRoutes, { prefix: '/api/v1' })
  await app.register(tradeRoutes, { prefix: '/api/v1' })
  await app.register(walletRoutes, { prefix: '/api/v1' })
  await app.register(kycRoutes, { prefix: '/api/v1' })
  await app.register(userRoutes, { prefix: '/api/v1' })
  await app.register(dashboardRoutes, { prefix: '/api/v1' })
  await app.register(merchantRoutes, { prefix: '/api/v1' })
  await app.register(instantBuyRoutes, { prefix: '/api/v1' })
  await app.register(disputeRoutes, { prefix: '/api/v1' })
  await app.register(notificationRoutes, { prefix: '/api/v1' })
  await app.register(referralRoutes, { prefix: '/api/v1' })
  await app.register(leaderboardRoutes, { prefix: '/api/v1' })
  await app.register(uploadRoutes, { prefix: '/api/v1' })
  await app.register(webhookRoutes, { prefix: '/api/v1' })
  await app.register(rateAlertRoutes, { prefix: '/api/v1' })
  await app.register(savedTermsRoutes, { prefix: '/api/v1' })
  await app.register(gasFeeRoutes, { prefix: '/api/v1' })
  await app.register(merchantGasRoutes, { prefix: '/api/v1' })
  await app.register(adminRoutes, { prefix: '/api/v1' })
  await app.register(ctmTokenRoutes, { prefix: '/api/v1' })
  await app.register(ctmListingRoutes, { prefix: '/api/v1' })
  await app.register(ctmRequestRoutes, { prefix: '/api/v1' })
  await app.register(ctmTradeRoutes, { prefix: '/api/v1' })
  await app.register(ctmMerchantRoutes, { prefix: '/api/v1' })
  await app.register(ctmAdminRoutes, { prefix: '/api/v1' })
  await app.register(ctmBidRoutes, { prefix: '/api/v1' })
  await app.register(adBidRoutes, { prefix: '/api/v1' })
  await app.register(pushRoutes, { prefix: '/api/v1' })
  await app.register(sseRoutes, { prefix: '/api/v1' })
  await app.register(adminNotificationRoutes, { prefix: '/api/v1' })
  await app.register(logosRoutes, { prefix: '/api/v1' })
  await app.register(supportRoutes, { prefix: '/api/v1' })
  await app.register(appealRoutes, { prefix: '/api/v1' })
  await app.register(telegramRoutes, { prefix: '/api/v1' })
  await app.register(accountLinkRoutes, { prefix: '/api/v1' })
  await app.register(announcementRoutes, { prefix: '/api/v1' })
  await app.register(blogRoutes, { prefix: '/api/v1' })
  await app.register(airdropRoutes, { prefix: '/api/v1' })
}
